# Generated by Django 4.2.5 on 2023-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_feet', models.PositiveIntegerField()),
                ('no_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_offices', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
